services:
  backend:
    image: varunkorada/student-assistant:v1
    ports:
      - "8000:8000"
    volumes:
      - rag_files:/app/source_files
      - rag_vectorstore:/app/chroma_db
    env_file:
      - .env
    restart: unless-stopped

volumes:
  rag_files:
  rag_vectorstore: